### PR TITLE
Fix: Building fails at `YarnInstall` and `Restore`

### PR DESCRIPTION
**Pull request by Booksbaum**
`.\fake.cmd run .\build.fsx` fails on Windows for two targets: `YarnInstall` and `Restore`

First `YarnInstall` fails with
> Unsupported log file format. Latest supported version is 7, the log file has version 9.

<details>
  <summary>Output of build</summary>

```  
❯ .\fake.cmd run .\build.fsx

E:\prog\fsharp\html-to-elmish>dotnet restore build.proj
  Determining projects to restore...
  All projects are up-to-date for restore.

E:\prog\fsharp\html-to-elmish>dotnet fake run .\build.fsx
The last restore is still up to date. Nothing left to do.
run Build
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== Setup
      <== Restore
         <== YarnInstall
            <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - YarnInstall
Group - 3
  - Restore
Group - 4
  - Setup
Group - 5
  - Build
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0159934
Starting target 'YarnInstall'
.> "C:\Users\me\AppData\Roaming\npm\yarn.CMD" install (In: false, Out: false, Err: false)
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error E:\prog\fsharp\html-to-elmish\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\prog\fsharp\html-to-elmish\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe E:\prog\fsharp\html-to-elmish\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.8.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\Python27\python2.EXE
gyp verb check python version `C:\Python27\python2.EXE -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.8.0
gyp verb command install [ '14.8.0' ]
gyp verb install input version string "14.8.0"
gyp verb install installing version: 14.8.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.8.0
gyp verb build dir attempting to create "build" dir: E:\prog\fsharp\html-to-elmish\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\prog\fsharp\html-to-elmish\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\prog\fsharp\html-to-elmish\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\prog\fsharp\html-to-elmish\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\prog\fsharp\html-to-elmish\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [
gyp info spawn args   'E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\me\\.node-gyp\\14.8.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\me\\.node-gyp\\14.8.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\me\\.node-gyp\\14.8.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\me\.node-gyp\14.8.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\prog\\fsharp\\html-to-elmish\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\prog\fsharp\html-to-elmish\node_modules\node-sass
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Finished (Failed) 'YarnInstall' in 00:00:04.1212012

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target        Duration
------        --------
Clean         00:00:00.0126607
YarnInstall   00:00:04.1209138   ('yarn install' task failed)
Restore       00:00:00           (skipped)
Setup         00:00:00           (skipped)
Build         00:00:00           (skipped)
Total:        00:00:04.2240402
Status:       Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'YarnInstall' failed.
-> One or more errors occurred. ('yarn install' task failed)
-> 'yarn install' task failed
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Hint: Detected paket version '5.206.0' in your paket.dependencies file bootstrapper arguments, consider locking the version to '5.196.2' in your dependencies file (E:\prog\fsharp\html-to-elmish\paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Performance:
 - Cli parsing: 145 milliseconds
 - Packages: 10 milliseconds
 - Script analyzing: 13 milliseconds
 - Script running: 4 seconds
 - Script cleanup: 7 milliseconds
 - Runtime: 4 seconds
```
</details>

Failure occurs while running `node-sass` -> `node-gyp`. Updating `node-sass` fixed it (probably because old version doesn't support node 14 (which i have installed)).

<br/>
<br/>

After that's fixed, fake fails at target `Restore` with
> Unsupported log file format. Latest supported version is 7, the log file has version 9.

<details>
  <summary>Output of build</summary>

```  
❯ .\fake.cmd run .\build.fsx

E:\prog\fsharp\html-to-elmish>dotnet restore build.proj
  Determining projects to restore...
  All projects are up-to-date for restore.

E:\prog\fsharp\html-to-elmish>dotnet fake run .\build.fsx
The last restore is still up to date. Nothing left to do.
run Build
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== Setup
      <== Restore
         <== YarnInstall
            <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - YarnInstall
Group - 3
  - Restore
Group - 4
  - Setup
Group - 5
  - Build
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0155355
Starting target 'YarnInstall'
.> "C:\Users\me\AppData\Roaming\npm\yarn.CMD" install (In: false, Out: false, Err: false)
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.32s.
Finished (Success) 'YarnInstall' in 00:00:00.5473220
Starting target 'Restore'
Starting task 'DotNet:restore': E:\prog\fsharp\html-to-elmish\src\HtmlConverter\Fable.HtmlConverter.fsproj
E:\prog\fsharp\html-to-elmish> "C:\Program Files\dotnet\dotnet.EXE" msbuild /version /nologo (In: false, Out: true, Err: true)
16.8.0.42503
E:\prog\fsharp\html-to-elmish> "C:\Program Files\dotnet\dotnet.EXE" restore "E:\prog\fsharp\html-to-elmish\src\HtmlConverter\Fable.HtmlConverter.fsproj" /nodeReuse:False "/bl:C:\Users\me\AppData\Local\Temp\tmpF3DD.tmp.binlog" (In: false, Out: false, Err: false)
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20427.1\MSBuild.dll -nologo -maxcpucount -target:Restore -verbosity:m /bl:C:\Users\me\AppData\Local\Temp\tmpF3DD.tmp.binlog /nodeReuse:False E:\prog\fsharp\html-to-elmish\src\HtmlConverter\Fable.HtmlConverter.fsproj
  Determining projects to restore...
  Paket version 5.206.0
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 43 milliseconds
  Paket version 5.206.0
  Starting restore process.
  Performance:
   - Disk IO: 4 milliseconds
   - Runtime: 627 milliseconds
  Restored E:\prog\fsharp\html-to-elmish\src\HtmlConverter\Fable.HtmlConverter.fsproj (in 78 ms).
Finished (Failed) 'DotNet:restore' in 00:00:02.3540680
Finished (Failed) 'Restore' in 00:00:02.3563226

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target        Duration
------        --------
Clean         00:00:00.0122968
YarnInstall   00:00:00.5471240
Restore       00:00:02.3560796   (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
Setup         00:00:00           (skipped)
Build         00:00:00           (skipped)
Total:        00:00:03.0046534
Status:       Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Restore' failed.
-> One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
-> NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Hint: Detected paket version '5.206.0' in your paket.dependencies file bootstrapper arguments, consider locking the version to '5.196.2' in your dependencies file (E:\prog\fsharp\html-to-elmish\paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Performance:
 - Cli parsing: 142 milliseconds
 - Packages: 9 milliseconds
 - Script analyzing: 12 milliseconds
 - Script running: 3 seconds
 - Script cleanup: 7 milliseconds
 - Runtime: 3 seconds
```
</details>

In the process of fixing it (updating `group netcorebuild`), I moved fake and paket to `dotnet tool`. Updating with existing `.paket/paket.exe` resulted in the same error message. (And `dotnet-fake` is deprecated.)

### CODE REVIEW

**Comment by Booksbaum** [comment]
Hm, `dotnet tool restore` fails on Mac. There doesn't seem to be a restore command?:
```
Usage: dotnet tool [options] [command]

Options:
  -h, --help   Show command line help.

Commands:
  install <PACKAGE_ID>     Install a tool for use on the command line.
  uninstall <PACKAGE_ID>   Uninstall a tool from the current development environment.
  update <PACKAGE_ID>      Update a tool to the latest stable version.
  list                     List tools installed in the current development environment.
  No executable found matching command "dotnet-paket"
/Users/runner/work/1/s/.paket/Paket.Restore.targets(171,5): error MSB3073: The command "dotnet paket restore" exited with code 1. [/Users/runner/work/1/s/build.proj]
No executable found matching command "dotnet-fake"
```
Seems like Mac uses a different .Net Core version than Linux & Windows (`SDK Version: 3.1.401` while Mac doesn't specify its version)

**Comment by cartermp** [comment]
I think to fix the restore issue this PR will have to add a `global.json` like so:

```json

{
  "sdk": {
    "version": "3.1.401",
    "rollForward": "minor"
  }
}
```

The azure pipelines definition is also a tad out of date:

* Windows `vmImage` should be: `vmImage: windows-2019`
* macOS vm should be `vmImage: macOS-latest`
*  linux vm should be `vmImage: ubuntu-latest`

And needs a new step in the task list to install .NET Core based on the globaljson

```yaml
- task: UseDotNet@2
  displayName: 'Install .NET Core based on global.json'
  inputs:
    useGlobalJson: true
```

Otherwise it will just use whatever is on the machines based on what I can see

**Comment by cartermp** [comment]
oof, now a bunch of different errors :(

**Comment by Booksbaum** [comment]
Well ... at least I found another bug :D .... (-> always dev build)

<br/>
<br/>

Building doesn't seem to produce any js output:
no output for fable-compile:
```
/Users/runner/work/1/s/node_modules/.bin/webpack --config src/WebApp/webpack.config.js --mode production
Bundling for production...
fable-compiler 2.1.12
// here should be a bunch of output what it's compiling 
Done in 11.76s.
```
and no file to unit test:
```
No files were found matching: tests/dist/bundle.js
```

On linux there's at least an error message:
```
$ /home/vsts/work/1/s/node_modules/.bin/webpack --config tests/webpack.config.js --mode production
Bundling for production...
fable-compiler 2.1.12
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at /home/vsts/work/1/s/node_modules/fable-compiler/dist/index.js:85:29
    at new Promise (<anonymous>)
    at Object.send (/home/vsts/work/1/s/node_modules/fable-compiler/dist/index.js:82:20)
    at Object.Loader (/home/vsts/work/1/s/node_modules/fable-loader/index.js:76:43)
    at LOADER_EXECUTION (/home/vsts/work/1/s/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/vsts/work/1/s/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/vsts/work/1/s/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/vsts/work/1/s/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/vsts/work/1/s/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /home/vsts/work/1/s/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /home/vsts/work/1/s/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
error Command failed with exit code 1.
```

Seems like on windows & mac fable fails silently?

**Comment by Booksbaum** [comment]
Ok....solution: just upgrade everything: #22 

I have no idea why this doesn't work -- but the updated stuff works  

Anyway: I'll close this. #22 contains everything this PR does.

**Pull request closed without merging**
