### PR TITLE
Upgrade Fable

### PR DESCRIPTION
**Pull request by Booksbaum**
Upgrade fable to new version. There are a couple of changes from the one currently used (like changed namespaces or different behaviour for dictionaries with non-existing keys).
-> Not compatible with current `Fable.HtmlConverter` nuget package!

Required to upgrade ionide to newest fable version: ionide/ionide-vscode-fsharp#1415

Note: based on #21 (because I need the project to build...), so Mac job will probably fail (but linux & windows should succeed).

### CODE REVIEW

**Comment by cartermp** [comment]
Weirdly the macOS job failed. maybe close/reopen to see if it was just a fluke?

**Comment by Booksbaum** [comment]
Ok, changes from #21 are merged, tests are green -> should be done


I thought about upgrading the other dependencies too (currently it's just fable) -- but just like fable, these are quite outdated and require more than just `yarn upgrade`. Will probably do that nevertheless. But over the next days, and in a different PR.

**Comment by cartermp** [comment]
@MangelMaxime can you take a look? This will unblock Ionide moving to an updated Fable

**Comment by MangelMaxime** [comment]
@Booksbaum @cartermp 

Hello, sorry for the delay kind of lacking of motivation nowdays.

@cartermp When I try to package the NuGet I get an "error".

```
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Fable.HtmlConverter -> C:\Users\Maxime\Workspaces\Github\MangelMaxime\html-to-elmish\src\HtmlConverter\bin\Debug\netstandard2.0\Fable.HtmlConverter.dll
C:\Program Files\dotnet\sdk\3.1.402\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error MSB4181: The "PackTask" task returned false but did not log an error. [C:\Users\Maxime\Workspaces\Github\MangelMaxime\html-to-elmish\src\HtmlConverter\Fable.HtmlConverter.fsproj]
```

But as you can see the error message is not really useful. Could you please take a look at why it does't work? Or does it ring any bell to you?

To test it you need to run:

1. `./fake.sh run build.fsx -t RunTests` <- Setup everything on the repo
2. `cd src/HtmlConverter`
3. `dotnet pack -c Release`

**Comment by cartermp** [comment]
Thanks! Let me try it out.

**Comment by MangelMaxime** [comment]
@cartermp Reverting to dotnet 3.1.300 allowed me to package the library.

@Booksbaum 

I just released version 2.1.0 please tell me if I need to do something else.

**Comment by cartermp** [comment]
Yeah, looks like there was a regression in NuGet. Another workaround that works for now is to ensure that this is set to `true` everywhere in the Paket.Restore.targets file:

```xml
<ContinuePackingAfterGeneratingNuspec>true</ContinuePackingAfterGeneratingNuspec>
```

This lets you use the latest SDK without issue.

Apparently .NET 5 RC2 will have the fix for this though, so I'll file a tracking issue here to upgrade to that for sanity's sake

**Comment by cartermp** [comment]
Thank you @MangelMaxime! This is the last dependency for https://github.com/ionide/ionide-vscode-fsharp/pull/1415

And closes https://github.com/ionide/ionide-vscode-fsharp/issues/1036 😄

**Pull request merged**
